services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app
    environment:
      - PORT=5001
    depends_on:
      - frontend
      - admin

  frontend:
    build: .
    ports:
      - 3011:3011
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - PORT=3011

  admin:
    build: .
    ports:
      - 3010:3010
    volumes:
      - ./admin:/app
      - ./admin/node_modules:/app/node_modules
    environment:
      - PORT=3010
