services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app
    environment:
      - PORT=5001
    command: npm install && npm start  # ✅ ติดตั้ง dependencies ก่อนรัน
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3011:3011
    volumes:
      - ./frontend:/app
      - /app/node_modules  # ✅ ป้องกัน node_modules หาย
    environment:
      - PORT=3011
    command: npm install && npm run dev  # ✅ ติดตั้ง vite ก่อน

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - 3010:3010
    volumes:
      - ./admin:/app
      - /app/node_modules  # ✅ ป้องกัน node_modules หาย
    environment:
      - PORT=3010
    command: npm install && npm run dev 
